bones:add_crop({
    {"farming:ananas_", 8},
    {"farming:bean_", 6},
    {"farming:beetroot_", 5},
    {"farming:blueberry_", 4},
    {"farming:carrot_", 4},
    {"farming:chili_", 8},
    {"farming:cocoa_", 6},
    {"farming:corn_", 8},
    {"farming:cucumber_", 4},
    {"farming:garlic_", 5},
    {"farming:grape_", 8},
    {"farming:hemp_", 8},
    {"farming:huckleberry_", 5},
    {"farming:onion_", 5},
    {"farming:pea_", 5},
    {"farming:potato_", 5},
    {"farming:raspberry_", 4},
    {"farming:rice_", 8},
    {"farming:strawberry_", 4},
    {"farming:tomato_", 8}
})
