hbhunger.register_food("default:apple", 2)

hbhunger.register_food('farming:bread', 5)

hbhunger.register_food('farming:ananas', 7)
hbhunger.register_food('farming:beetroot', 1)
hbhunger.register_food('farming:blueberry', 1)
hbhunger.register_food('farming:carrot', 2)
hbhunger.register_food('farming:chili', 1, "", 1)
hbhunger.register_food('farming:cucumber', 2)
hbhunger.register_food('farming:garlic', 1, "", 1)
hbhunger.register_food('farming:grape', 3)
hbhunger.register_food('farming:huckleberry', 1)
hbhunger.register_food('farming:lettuce', 2)
hbhunger.register_food('farming:onion', 2, "", 1)
hbhunger.register_food('farming:pea', 0.5)
hbhunger.register_food('farming:peanut', 0.5)
hbhunger.register_food('farming:potato', 2)
hbhunger.register_food('farming:potato_baked', 3)
hbhunger.register_food('farming:raspberry', 1)
hbhunger.register_food('farming:strawberry', 1)
hbhunger.register_food('farming:tomato', 1)

hbhunger.register_food('farming:salt', -1)
hbhunger.register_food('farming:sugar',-1)
hbhunger.register_food('farming:jam_ananas', -1, "vessels:glass_jar")
hbhunger.register_food('farming:jam_blueberry', -1, "vessels:glass_jar")
hbhunger.register_food('farming:jam_raspberry', -1, "vessels:glass_jar")
hbhunger.register_food('farming:jam_strawberry', -1, "vessels:glass_jar")
hbhunger.register_food('farming:jam_huckleberry', -1, "vessels:glass_jar")
hbhunger.register_food('farming:peanut_butter', -1, "vessels:glass_jar")

hbhunger.register_food('farming:bandit_burger', 7)
hbhunger.register_food('farming:beans_with_onion', 15, 'farming:bowl')
--hbhunger.register_food('farming:beetroot_soup',4, 'farming:bowl')
--hbhunger.register_food('farming:blueberry_muffin', 4)
hbhunger.register_food('farming:blueberry_pie_dough', 5, "", 1)
hbhunger.register_food('farming:blueberry_pie', 7)
hbhunger.register_food('farming:bread_dough', 3, "", 1)
hbhunger.register_food('farming:burger', 9)
hbhunger.register_food('farming:carrot_cake_dough', 5, "", 1)
hbhunger.register_food('farming:carrot_cake', 7)
--hbhunger.register_food('farming:chili_bowl', 7, 'farming:bowl')
--hbhunger.register_food('farming:chocolate_dark', 2)
hbhunger.register_food('farming:cookie', 2)
hbhunger.register_food('farming:corn_boiled', 4)
hbhunger.register_food('farming:corn_bread', 6)
-- hbhunger.register_food('farming:donut', 2)
-- hbhunger.register_food('farming:donut_apple', 3)
-- hbhunger.register_food('farming:donut_chocolate', 2)
hbhunger.register_food('farming:garlic_bread', 2)
hbhunger.register_food('farming:huckleberry_pie', 7)
hbhunger.register_food('farming:jam_ananas_sandwich', 4)
hbhunger.register_food('farming:jam_blueberry_sandwich', 4)
hbhunger.register_food('farming:jam_huckleberry_sandwich', 4)
hbhunger.register_food('farming:jam_raspberry_sandwich', 4)
hbhunger.register_food('farming:jam_strawberry_sandwich', 4)
hbhunger.register_food('farming:jelly_ananas', 4)
hbhunger.register_food('farming:jelly_blueberry', 4)
hbhunger.register_food('farming:jelly_huckleberry', 4)
hbhunger.register_food('farming:jelly_raspberry', 4)
hbhunger.register_food('farming:jelly_strawberry', 4)
hbhunger.register_food('farming:meatloaf_raw', 5, "", 1)
hbhunger.register_food('farming:meatloaf', 7)
hbhunger.register_food('farming:milkshake_blueberry', 4, "vessels:glass_jar")
hbhunger.register_food('farming:milkshake_raspberry', 4, "vessels:glass_jar")
hbhunger.register_food('farming:milkshake_strawberry', 4, "vessels:glass_jar")
hbhunger.register_food('farming:minced_meat', 2, "", 1)
--hbhunger.register_food('farming:pea_soup', 7, 'farming:bowl')
--hbhunger.register_food('farming:potato_salad', 3)
hbhunger.register_food('farming:peanut_butter_sandwich', 4)
hbhunger.register_food('farming:potato_mashed', 7, 'farming:bowl')
hbhunger.register_food('farming:raspberry_pie_dough', 5, "", 1)
hbhunger.register_food('farming:raspberry_pie', 7)
hbhunger.register_food('farming:rizibizi', 7, 'farming:bowl')
hbhunger.register_food('farming:rice_cooked', 5, 'farming:bowl')
hbhunger.register_food('farming:strawberry_cake_dough', 5, "", 1)
hbhunger.register_food('farming:strawberry_cake', 7)
hbhunger.register_food('farming:tomato_juice', 1, 'vessels:glass_bottle')

hbhunger.register_food('fishing:clownfish', 1, "", 1 )
hbhunger.register_food('fishing:salmon', 2, "", 1 )
hbhunger.register_food('fishing:salmon_cooked', 4 )
hbhunger.register_food('fishing:tuna', 2, "", 1 )
hbhunger.register_food('fishing:tuna_cooked', 4 )

hbhunger.register_food('flowers:mushroom_brown', 1 )
hbhunger.register_food('flowers:mushroom_red', 1, "", 2 )

hbhunger.register_food("mobs:cheese", 4)
hbhunger.register_food("mobs:meat", 8)
hbhunger.register_food("mobs:meat_raw", 4)
hbhunger.register_food("mobs:rat_cooked", 4)
hbhunger.register_food("mobs:honey", 2)
hbhunger.register_food("mobs:pork_raw", 3, "", 3)
hbhunger.register_food("mobs:pork_cooked", 8)
hbhunger.register_food("mobs:chicken_cooked", 6)
hbhunger.register_food("mobs:chicken_raw", 2, "", 3)
hbhunger.register_food("mobs:chicken_egg_fried", 2)
hbhunger.register_food("mobs:bucket_milk", 3, "bucket:bucket_empty")
