hbhunger.register_food("default:apple", 2)

hbhunger.register_food('foods:bread', 5)

hbhunger.register_food('farming:ananas', 7)
hbhunger.register_food('farming:beetroot', 1)
hbhunger.register_food('farming:blueberry', 1)
hbhunger.register_food('farming:carrot', 2)
hbhunger.register_food('farming:corn_boiled', 4)
hbhunger.register_food('farming:cucumber', 2)
hbhunger.register_food('farming:garlic', 1, "", 1)
hbhunger.register_food('farming:grape', 3)
hbhunger.register_food('farming:huckleberry', 1)
hbhunger.register_food('farming:lettuce', 2)
hbhunger.register_food('farming:onion', 2, "", 1)
hbhunger.register_food('farming:peas', 0.5)
hbhunger.register_food('farming:peanut', 0.5)
hbhunger.register_food('farming:potato', 2)
hbhunger.register_food('farming:potato_baked', 3)
hbhunger.register_food('farming:raspberry', 1)
hbhunger.register_food('farming:strawberry', 1)
hbhunger.register_food('farming:tomato', 1)

hbhunger.register_food('foods:salt', -1)
hbhunger.register_food('foods:sugar',-1)
hbhunger.register_food('foods:jam_ananas', -1, "vessels:glass_jar")
hbhunger.register_food('foods:jam_blueberry', -1, "vessels:glass_jar")
hbhunger.register_food('foods:jam_grape', -1, "vessels:glass_jar")
hbhunger.register_food('foods:jam_raspberry', -1, "vessels:glass_jar")
hbhunger.register_food('foods:jam_strawberry', -1, "vessels:glass_jar")
hbhunger.register_food('foods:jam_huckleberry', -1, "vessels:glass_jar")
hbhunger.register_food('foods:peanut_butter', -1, "vessels:glass_jar")

hbhunger.register_food('foods:bandit_burger', 7)
hbhunger.register_food('foods:beans_with_onion', 15, 'foods:bowl')
hbhunger.register_food('foods:borsch', 10, 'foods:bowl')
hbhunger.register_food('foods:muffin_blueberry', 4)
hbhunger.register_food('foods:bread_dough', 3, "", 1)
hbhunger.register_food('foods:burger', 9)
hbhunger.register_food('foods:buterbrod', 5)
hbhunger.register_food('foods:buttered_bread_with_honey', 5)
hbhunger.register_food('foods:carrot_cake_dough', 5, "", 1)
hbhunger.register_food('foods:carrot_cake', 7)
hbhunger.register_food('foods:chicken_soup', 10, 'foods:bowl')
hbhunger.register_food('foods:chocolate', 2)
hbhunger.register_food('foods:cookie', 2)
hbhunger.register_food('foods:corn_bread', 6)
hbhunger.register_food('foods:garlic_bread', 2)
hbhunger.register_food('foods:jam_ananas_sandwich', 4)
hbhunger.register_food('foods:jam_blueberry_sandwich', 4)
hbhunger.register_food('foods:jam_grape_sandwich', 4)
hbhunger.register_food('foods:jam_huckleberry_sandwich', 4)
hbhunger.register_food('foods:jam_raspberry_sandwich', 4)
hbhunger.register_food('foods:jam_strawberry_sandwich', 4)
hbhunger.register_food('foods:jelly_ananas', 4)
hbhunger.register_food('foods:jelly_blueberry', 4)
hbhunger.register_food('foods:jelly_grape', 4)
hbhunger.register_food('foods:jelly_huckleberry', 4)
hbhunger.register_food('foods:jelly_raspberry', 4)
hbhunger.register_food('foods:jelly_strawberry', 4)
hbhunger.register_food('foods:meatloaf_unbaked', 5, "", 1)
hbhunger.register_food('foods:meatloaf', 7)
hbhunger.register_food('foods:milkshake_blueberry', 2, "vessels:glass_jar")
hbhunger.register_food('foods:milkshake_raspberry', 2, "vessels:glass_jar")
hbhunger.register_food('foods:milkshake_strawberry', 2, "vessels:glass_jar")
hbhunger.register_food('foods:minced_meat', 2, "", 1)
hbhunger.register_food('foods:muffin_blueberry', 4)
hbhunger.register_food('foods:peanut_butter_sandwich', 4)
hbhunger.register_food('foods:pie_apple', 7)
hbhunger.register_food('foods:pie_apple_dough', 5, "", 1)
hbhunger.register_food('foods:pie_blueberry', 7)
hbhunger.register_food('foods:pie_blueberry_dough', 5, "", 1)
hbhunger.register_food('foods:pie_huckleberry', 7)
hbhunger.register_food('foods:pie_huckleberry_dough', 5, "", 1)
hbhunger.register_food('foods:pie_raspberry', 7)
hbhunger.register_food('foods:pie_raspberry_dough', 5, "", 1)
hbhunger.register_food('foods:peas_mashed', 7, 'foods:bowl')
hbhunger.register_food('foods:popcorn', 4, 'foods:paper_bag')
hbhunger.register_food('foods:potato_mashed', 7, 'foods:bowl')
hbhunger.register_food('foods:rizibizi', 7, 'foods:bowl')
hbhunger.register_food('foods:rice_cooked', 5, 'foods:bowl')
hbhunger.register_food('foods:strawberry_cake_dough', 5, "", 1)
hbhunger.register_food('foods:strawberry_cake', 7)
hbhunger.register_food('foods:tomato_juice', 1, 'vessels:glass_bottle')

hbhunger.register_food('fishing:clownfish', 1, "", 1 )
hbhunger.register_food('fishing:salmon', 2, "", 1 )
hbhunger.register_food('fishing:salmon_cooked', 4 )
hbhunger.register_food('fishing:tuna', 2, "", 1 )
hbhunger.register_food('fishing:tuna_cooked', 4 )
hbhunger.register_food('fishing:shusi', 3)

hbhunger.register_food('flowers:mushroom_brown', 1 )
hbhunger.register_food('flowers:mushroom_red', 1, "", 2 )

hbhunger.register_food("mobs:cheese", 4)
hbhunger.register_food("mobs:meat", 8)
hbhunger.register_food("mobs:meat_raw", 4)
hbhunger.register_food("mobs:rat_cooked", 4)
hbhunger.register_food("mobs:honey", 2)
hbhunger.register_food("mobs:pork_raw", 3, "", 3)
hbhunger.register_food("mobs:pork_cooked", 8)
hbhunger.register_food("mobs:chicken_cooked", 6)
hbhunger.register_food("mobs:chicken_raw", 2, "", 3)
hbhunger.register_food("mobs:chicken_egg_fried", 2)
hbhunger.register_food("mobs:jar_milk", 1, "vessels:glass_jar")
